### ISSUE TITLE
Notebook-runtime missing

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll-plugin-observable#1]
I think maybe the notebook runtime is missing from a module. I'm still not completely familiar with the file resolution mechanism and am trying to figure out where to put the runtime in order to satisfy the requirements.

I've created an idyll project, installed the module, and tried to run it. To be more verbose though, here are the exact steps:

### Steps to reproduce:

Create an idyll project:

```
npm i -g idyll
idyll create
? In which directory would you like to install your post? observable-example
cd observable-example
npm i -D idyll-plugin-observable
```

Add to package.json:
```
  "compiler": {
    "postProcessors": ["idyll-plugin-observable"]
  }
```

Copy example code into `index.idyll`:

```
[Observable
  notebook:"https://observablehq.com/@mathisonian/d3-change-line-chart"
  showCells:`['chart']`
  variables:`{
    lineWidth: lineWidth,
    height: height
  }` /]
```

Start

```
$ idyll

Building Idyll project with output directory: build

{ Error: Cannot find module './lib/notebook-runtime/src/'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module._load (/Users/rreusser/node/idyll-lang/samples/observable-example/node_modules/idyll/src/node-config.js:23:29)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rreusser/node/idyll-lang/samples/observable-example/components/mathisonian-d3-change-line-chart.js:3:43)
    at Module._compile (module.js:635:30)
    at loader (/Users/rreusser/node/idyll-lang/samples/observable-example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rreusser/node/idyll-lang/samples/observable-example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module._load (/Users/rreusser/node/idyll-lang/samples/observable-example/node_modules/idyll/src/node-config.js:23:29)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.keys.forEach.key (/Users/rreusser/node/idyll-lang/samples/observable-example/node_modules/idyll/src/pipeline/parse.js:168:23) code: 'MODULE_NOT_FOUND' }
```

I've tried to put a copy of `./lib/notebook-runtime/src/` in every location I can think of, but it's not currently managing to find it.

It's probably something simply but any suggestions would be greatly appreciated!

**Comment by rreusser** [comment]
Ah, I see. It's in the generated code so has to go in `components/lib/notebook-runtime/src/`.

**Comment by rreusser** [comment]
The next issue I ran into was `undefined is not iterable (cannot read property Symbol(Symbol.iterator))`. It seems like it's having trouble binding to the variables, but perhaps that's something that needs some work and investigation more than it needs a detailed issue, so I'll focus on working through and understanding the code :)

**Comment by mathisonian** [comment]
Yes - sorry for all the troubles @rreusser. I'm having difficulties getting the runtime to load correctly from the npm package, and for some reason it seems to work okay when included in `lib/` like that, so I've had it set up that way for testing. 

I'm trying to make progress on these issues today, and will post here as that happens.

**Comment by rreusser** [comment]
Awesome, thanks! No pressure here, but this seems like such a cool idea. I was getting pretty confused and found I had to back up a bit and trying to read up on the runtime:

- https://observablehq.com/@observablehq/downloading-and-embedding-notebooks
- https://observablehq.com/@jashkenas/ouroboros-a-notebook-embeds-itself

**Comment by mathisonian** [comment]
Agreed @rreusser, I'd really like to get this to a practically usable point. I think I've made some progress and eliminated the need for a `lib` directory. 

The following workflow is now functioning as expected for me, starting from a fresh project. Steps:

1. Run `idyll create` to make a new project, `cd` into the new directory
2. Install `idyll-plugin-observable` and add it to `idyll.compiler.postProcessors` in `package.json`. 
3. Add the following code into `index.idyll`:
```
[var name:"lineWidth" value:5 /]
[Range min:1 max:30 value:lineWidth /]

[Observable
  notebook:"https://observablehq.com/@mathisonian/d3-change-line-chart"
  showCells:`['chart']`
  variables:`{
    lineWidth: lineWidth
  }` /]
```
4. Run `idyll`. Fails with component not found error. 
5. Run `idyll` again. A single line chart should appear, with its lineWidth parameterized by an Idyll slider.

The reason that the compile fails the first time is that a map of available components is made before the compile step happens, and because the plugin generates the necessary component after this map is already created, it isn't found.

**Comment by mathisonian** [comment]
This is currently using `v1` of the exported notebook instead of `v3`, because the older version includes all of the dependencies packaged into one file. The newer version opts to instead perform `import notebook from 'https://url/'` which doesn't play nice with browserify. 

I'm not sure if this is going to become an issue, or we can rely on this version to continue functioning, maybe something to check with the Observable folks on.

**Comment by rreusser** [comment]
Makes sense. I’ll try again. Also, I had asked about v3 so tacked on a question about v1: https://talk.observablehq.com/t/is-v-3-correct-when-requesting-notebook-js/1971/2

**Comment by rreusser** [comment]
I think there's more work required to get this plugin just right (two-way binding, maybe tarball instead of js API?), but this specific issue is resolved so that I'll close.
